language: python
python: 3.5

services:
  - mysql

env:
  global:
    - PW_TEST_DB_USER=travis
    - PW_TEST_DB_PASS=""
    - PW_SKIP_BROWSER_TESTS=yes
  matrix:
    - TOX_ENV=py27-django16
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py34-django16
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django110
    - TOX_ENV=py35-django18
    - TOX_ENV=py35-django19
    - TOX_ENV=py35-django110

before_script:
  - mysql -e 'create database patchwork character set utf8;'

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
