site_name: patchwork
site_url: http://jk.ozlabs.org/projects/patchwork/
site_description: patchwork - the web-based patch tracking system

repo_url: git://github.com/getpatchwork/patchwork

pages:
 - Home: 'index.md'
 - Development Guide:
   - Installation: 'development.md'
   - Contributing: 'contributing.md'
   - Release Process: 'releasing.md'
 - Deployment Guide:
   - Installation: 'deployment.md'
   - Upgrading: 'upgrading.md'
   - API: 'api.md'
