site_name: patchwork
site_url: http://jk.ozlabs.org/projects/patchwork/
site_description: patchwork - the web-based patch tracking system

repo_url: git://github.com/getpatchwork/patchwork

pages:
 - Home: 'index.md'
 - Development Guide:
   - Installation: 'development/installation.md'
   - Contributing: 'development/contributing.md'
   - Release Process: 'development/releasing.md'
   - XML-RPC API: 'development/xmlrpc.md'
 - Deployment Guide:
   - Installation: 'deployment/installation.md'
   - Upgrading: 'deployment/upgrading.md'
 - Usage Guide:
   - REST API: 'usage/rest.md'
   - XML-RPC API: 'usage/xmlrpc.md'
